/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc.h"

float *
adicao_100_svc(valores *argp, struct svc_req *rqstp)
{
	static float  result;

	printf("Cliente solicita: \n");
	printf("Operação de adição para %.2f e %.2f", argp->valor1, argp->valor2);
	result = argp->valor1 + argp->valor2;
	printf("Resultado da adição: %.2f \n\n", result);

	return &result;
}

float *
subtracao_100_svc(valores *argp, struct svc_req *rqstp)
{
	static float  result;

	printf("Cliente solicita: \n");
	printf("Operação de subtração para %.2f e %.2f", argp->valor1, argp->valor2);
	result = argp->valor1 - argp->valor2;
	printf("Resultado da subtração: %.2f \n\n", result);

	return &result;
}

float *
divisao_100_svc(valores *argp, struct svc_req *rqstp)
{
	static float  result;

	printf("Cliente solicita: \n");
	printf("Operação de divisao para %.2f e %.2f", argp->valor1, argp->valor2);
	result = argp->valor1 / argp->valor2;
	printf("Resultado da divisao: %.2f \n\n", result);

	return &result;
}

float *
multiplicacao_100_svc(valores *argp, struct svc_req *rqstp)
{
	static float  result;

	printf("Cliente solicita: \n");
	printf("Operação de multiplicacao para %.2f e %.2f", argp->valor1, argp->valor2);
	result = argp->valor1 * argp->valor2;
	printf("Resultado da multiplicacao: %.2f \n\n", result);

	return &result;
}
